version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: aim_ahead_api
    ports:
      - "5432:5432"
    volumes:
      - my_local_dbdata:/var/lib/postgresql/data  # Persist database data

volumes:
  my_local_dbdata:
