version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - my_local_dbdata:/var/lib/postgresql/data

volumes:
  my_local_dbdata:
