[tool.black]
exclude = '''
/(
    src/migrations/*
)/
'''

[tool.isort]
skip_glob = ["src/migrations/*"]

[tool.flake8]
exclude = ["src/migrations/"]
max-line-length = 88
ignore = ["E203", "W503"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests/*.py",
]

[tool.coverage.run]
branch = true
source = ["src"]
omit = [
    "src/migrations/*"
]

[tool.coverage.report]
fail_under = 90  # Your desired coverage threshold




